const SHORTS_DURATION = 40;
const SHOW_MORE_SMALL_WIDTH = 2;
const SHOW_MORE_MIDDLE_WIDTH = 3;
const SHOW_MORE_LARGE_WIDTH = 4;
const NAME_REGEX = "^[A-Za-zА-Яа-яЁё /s -]+$";
const EMAIL_REGEX = "[a-z0-9]+@[a-z]+\\.[a-z]{2,5}";

export {
  SHORTS_DURATION,
  SHOW_MORE_SMALL_WIDTH,
  SHOW_MORE_MIDDLE_WIDTH,
  SHOW_MORE_LARGE_WIDTH,
  NAME_REGEX,
  EMAIL_REGEX,
};